USE THITRACNGHIEM;
GO

IF NOT EXISTS (SELECT 1 FROM MONHOC WHERE MAMH = 'CSDL') INSERT INTO MONHOC (MAMH, TENMH) VALUES ('CSDL', N'Co so du lieu');
IF NOT EXISTS (SELECT 1 FROM MONHOC WHERE MAMH = 'MMT') INSERT INTO MONHOC (MAMH, TENMH) VALUES ('MMT', N'Mang may tinh');
IF NOT EXISTS (SELECT 1 FROM MONHOC WHERE MAMH = 'CTDL') INSERT INTO MONHOC (MAMH, TENMH) VALUES ('CTDL', N'Cau truc du lieu');
IF NOT EXISTS (SELECT 1 FROM MONHOC WHERE MAMH = 'LTHDT') INSERT INTO MONHOC (MAMH, TENMH) VALUES ('LTHDT', N'Lap trinh huong doi tuong');
IF NOT EXISTS (SELECT 1 FROM MONHOC WHERE MAMH = 'HQT') INSERT INTO MONHOC (MAMH, TENMH) VALUES ('HQT', N'He quan tri CSDL');
IF NOT EXISTS (SELECT 1 FROM MONHOC WHERE MAMH = 'ATTT') INSERT INTO MONHOC (MAMH, TENMH) VALUES ('ATTT', N'An toan thong tin');
IF NOT EXISTS (SELECT 1 FROM MONHOC WHERE MAMH = 'CNPM') INSERT INTO MONHOC (MAMH, TENMH) VALUES ('CNPM', N'Cong nghe phan mem');
GO

IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = 'D21CQCN01') INSERT INTO LOP (MALOP, TENLOP) VALUES ('D21CQCN01', N'Dai hoc CNTT 01');
IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = 'D21CQCN02') INSERT INTO LOP (MALOP, TENLOP) VALUES ('D21CQCN02', N'Dai hoc CNTT 02');
IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = 'D21CQCN03') INSERT INTO LOP (MALOP, TENLOP) VALUES ('D21CQCN03', N'Dai hoc CNTT 03');
IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = 'D22CQCN01') INSERT INTO LOP (MALOP, TENLOP) VALUES ('D22CQCN01', N'Dai hoc CNTT K22 01');
IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = 'D22CQCN02') INSERT INTO LOP (MALOP, TENLOP) VALUES ('D22CQCN02', N'Dai hoc CNTT K22 02');
IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = 'D23CQCN01') INSERT INTO LOP (MALOP, TENLOP) VALUES ('D23CQCN01', N'Dai hoc CNTT K23 01');
IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = 'D23CQCN02') INSERT INTO LOP (MALOP, TENLOP) VALUES ('D23CQCN02', N'Dai hoc CNTT K23 02');
GO

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN WHERE MAGV = 'PGV001') INSERT INTO GIAOVIEN (MAGV, HO, TEN, SODTLL, DIACHI) VALUES ('PGV001', N'Phong', N'GiaoVu', '', '');
IF NOT EXISTS (SELECT 1 FROM GIAOVIEN WHERE MAGV = 'GV001') INSERT INTO GIAOVIEN (MAGV, HO, TEN, SODTLL, DIACHI) VALUES ('GV001', N'Nguyen Van', N'An', '', '');
IF NOT EXISTS (SELECT 1 FROM GIAOVIEN WHERE MAGV = 'GV002') INSERT INTO GIAOVIEN (MAGV, HO, TEN, SODTLL, DIACHI) VALUES ('GV002', N'Tran Thi', N'Binh', '', '');
IF NOT EXISTS (SELECT 1 FROM GIAOVIEN WHERE MAGV = 'GV003') INSERT INTO GIAOVIEN (MAGV, HO, TEN, SODTLL, DIACHI) VALUES ('GV003', N'Le Quoc', N'Dat', '', N'TP HCM');
IF NOT EXISTS (SELECT 1 FROM GIAOVIEN WHERE MAGV = 'GV004') INSERT INTO GIAOVIEN (MAGV, HO, TEN, SODTLL, DIACHI) VALUES ('GV004', N'Pham Thanh', N'Ha', '', N'Dong Nai');
GO

DECLARE @login sysname, @password nvarchar(255), @user sysname, @role sysname, @sql nvarchar(max);

DECLARE account_cursor CURSOR LOCAL FAST_FORWARD FOR
SELECT login_name, password_value, user_name, role_name
FROM (VALUES
    ('GV003', '123456', 'GV003', 'GIANGVIEN'),
    ('GV004', '123456', 'GV004', 'GIANGVIEN')
) AS accounts(login_name, password_value, user_name, role_name);

OPEN account_cursor;
FETCH NEXT FROM account_cursor INTO @login, @password, @user, @role;
WHILE @@FETCH_STATUS = 0
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = @role)
    BEGIN
        SET @sql = N'CREATE ROLE ' + QUOTENAME(@role);
        EXEC(@sql);
    END

    IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = @login)
    BEGIN
        SET @sql = N'CREATE LOGIN ' + QUOTENAME(@login)
            + N' WITH PASSWORD = ' + QUOTENAME(@password, '''')
            + N', DEFAULT_DATABASE = [THITRACNGHIEM], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF';
        EXEC(@sql);
    END
    ELSE
    BEGIN
        SET @sql = N'ALTER LOGIN ' + QUOTENAME(@login)
            + N' WITH PASSWORD = ' + QUOTENAME(@password, '''')
            + N', DEFAULT_DATABASE = [THITRACNGHIEM], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF';
        EXEC(@sql);
    END

    IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = @user)
    BEGIN
        SET @sql = N'CREATE USER ' + QUOTENAME(@user) + N' FOR LOGIN ' + QUOTENAME(@login);
        EXEC(@sql);
    END

    IF NOT EXISTS (
        SELECT 1
        FROM sys.database_role_members drm
        JOIN sys.database_principals rp ON drm.role_principal_id = rp.principal_id
        JOIN sys.database_principals up ON drm.member_principal_id = up.principal_id
        WHERE rp.name = @role AND up.name = @user
    )
    BEGIN
        SET @sql = N'ALTER ROLE ' + QUOTENAME(@role) + N' ADD MEMBER ' + QUOTENAME(@user);
        EXEC(@sql);
    END

    FETCH NEXT FROM account_cursor INTO @login, @password, @user, @role;
END
CLOSE account_cursor;
DEALLOCATE account_cursor;
GO

IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV004') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV004', N'Nguyen Hoai', N'Nam', '2004-01-11', N'TP HCM', 'D21CQCN02', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV005') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV005', N'Tran Minh', N'Thu', '2004-03-19', N'Tay Ninh', 'D21CQCN03', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV006') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV006', N'Pham Gia', N'Huy', '2004-05-23', N'Long An', 'D21CQCN03', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV007') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV007', N'Do Quynh', N'Anh', '2004-08-14', N'Binh Duong', 'D22CQCN01', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV008') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV008', N'Bui Thanh', N'Lam', '2004-10-05', N'Dong Nai', 'D22CQCN01', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV009') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV009', N'Vo Ngoc', N'Linh', '2004-12-01', N'TP HCM', 'D22CQCN02', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV010') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV010', N'Nguyen Bao', N'Khanh', '2005-01-09', N'TP HCM', 'D23CQCN01', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV011') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV011', N'Tran My', N'Duyen', '2005-04-17', N'Lam Dong', 'D23CQCN01', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV012') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV012', N'Ho Duc', N'Phuc', '2005-06-26', N'Binh Phuoc', 'D23CQCN01', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV013') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV013', N'Le Thao', N'Nhi', '2005-02-12', N'Dong Nai', 'D23CQCN02', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV014') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV014', N'Pham Minh', N'Kiet', '2005-07-30', N'Tay Ninh', 'D23CQCN02', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV015') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV015', N'Dang Gia', N'Bao', '2005-11-03', N'TP HCM', 'D23CQCN02', '123456');
GO

DECLARE @subjects TABLE (MAMH nchar(5), MAGV nchar(8));
INSERT INTO @subjects (MAMH, MAGV) VALUES ('CSDL', 'GV001'), ('CTDL', 'GV001'), ('HQT', 'GV001'), ('MMT', 'GV002'), ('LTHDT', 'GV002'), ('ATTT', 'GV003'), ('CNPM', 'GV004');

DECLARE @levels TABLE (TRINHDO char(1), DAP_AN char(1));
INSERT INTO @levels (TRINHDO, DAP_AN) VALUES ('A', 'A'), ('B', 'B'), ('C', 'C');

DECLARE @mamh nchar(5), @magv nchar(8), @level char(1), @answer char(1), @i int, @next_cauhoi int;
SELECT @next_cauhoi = ISNULL(MAX(CAUHOI), 0) FROM BODE;
DECLARE subject_cursor CURSOR LOCAL FAST_FORWARD FOR SELECT MAMH, MAGV FROM @subjects;
OPEN subject_cursor;
FETCH NEXT FROM subject_cursor INTO @mamh, @magv;
WHILE @@FETCH_STATUS = 0
BEGIN
    DECLARE level_cursor CURSOR LOCAL FAST_FORWARD FOR SELECT TRINHDO, DAP_AN FROM @levels;
    OPEN level_cursor;
    FETCH NEXT FROM level_cursor INTO @level, @answer;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @i = 1;
        WHILE @i <= 50
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM BODE
                WHERE MAMH = @mamh AND TRINHDO = @level AND NOIDUNG = CONCAT(RTRIM(@mamh), N' ', @level, N' demo cau ', @i)
            )
            BEGIN
                SET @next_cauhoi += 1;

                INSERT INTO BODE (CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV)
                VALUES (
                    @next_cauhoi,
                    @mamh,
                    @level,
                    CONCAT(RTRIM(@mamh), N' ', @level, N' demo cau ', @i),
                    CONCAT(N'Lua chon A cho cau ', @i),
                    CONCAT(N'Lua chon B cho cau ', @i),
                    CONCAT(N'Lua chon C cho cau ', @i),
                    CONCAT(N'Lua chon D cho cau ', @i),
                    @answer,
                    @magv
                );
            END
            SET @i += 1;
        END
        FETCH NEXT FROM level_cursor INTO @level, @answer;
    END
    CLOSE level_cursor;
    DEALLOCATE level_cursor;

    FETCH NEXT FROM subject_cursor INTO @mamh, @magv;
END
CLOSE subject_cursor;
DEALLOCATE subject_cursor;
GO

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN_DANGKY WHERE MALOP = 'D21CQCN01' AND MAMH = 'CTDL' AND LAN = 1)
    INSERT INTO GIAOVIEN_DANGKY (MALOP, MAMH, LAN, MAGV, TRINHDO, NGAYTHI, SOCAUTHI, THOIGIAN)
    VALUES ('D21CQCN01', 'CTDL', 1, 'GV001', 'B', DATEADD(DAY, 1, GETDATE()), 40, 30);

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN_DANGKY WHERE MALOP = 'D21CQCN02' AND MAMH = 'HQT' AND LAN = 1)
    INSERT INTO GIAOVIEN_DANGKY (MALOP, MAMH, LAN, MAGV, TRINHDO, NGAYTHI, SOCAUTHI, THOIGIAN)
    VALUES ('D21CQCN02', 'HQT', 1, 'GV001', 'A', DATEADD(DAY, 2, GETDATE()), 40, 30);

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN_DANGKY WHERE MALOP = 'D22CQCN01' AND MAMH = 'MMT' AND LAN = 1)
    INSERT INTO GIAOVIEN_DANGKY (MALOP, MAMH, LAN, MAGV, TRINHDO, NGAYTHI, SOCAUTHI, THOIGIAN)
    VALUES ('D22CQCN01', 'MMT', 1, 'GV002', 'B', DATEADD(DAY, 1, GETDATE()), 40, 30);

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN_DANGKY WHERE MALOP = 'D22CQCN02' AND MAMH = 'LTHDT' AND LAN = 1)
    INSERT INTO GIAOVIEN_DANGKY (MALOP, MAMH, LAN, MAGV, TRINHDO, NGAYTHI, SOCAUTHI, THOIGIAN)
    VALUES ('D22CQCN02', 'LTHDT', 1, 'GV002', 'C', DATEADD(DAY, 3, GETDATE()), 40, 30);

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN_DANGKY WHERE MALOP = 'D23CQCN01' AND MAMH = 'ATTT' AND LAN = 1)
    INSERT INTO GIAOVIEN_DANGKY (MALOP, MAMH, LAN, MAGV, TRINHDO, NGAYTHI, SOCAUTHI, THOIGIAN)
    VALUES ('D23CQCN01', 'ATTT', 1, 'GV003', 'A', DATEADD(DAY, 2, GETDATE()), 30, 25);

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN_DANGKY WHERE MALOP = 'D23CQCN02' AND MAMH = 'CNPM' AND LAN = 1)
    INSERT INTO GIAOVIEN_DANGKY (MALOP, MAMH, LAN, MAGV, TRINHDO, NGAYTHI, SOCAUTHI, THOIGIAN)
    VALUES ('D23CQCN02', 'CNPM', 1, 'GV004', 'B', DATEADD(DAY, 2, GETDATE()), 30, 25);

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN_DANGKY WHERE MALOP = 'D21CQCN03' AND MAMH = 'HQT' AND LAN = 1)
    INSERT INTO GIAOVIEN_DANGKY (MALOP, MAMH, LAN, MAGV, TRINHDO, NGAYTHI, SOCAUTHI, THOIGIAN)
    VALUES ('D21CQCN03', 'HQT', 1, 'PGV001', 'C', DATEADD(DAY, 4, GETDATE()), 30, 25);
GO

IF NOT EXISTS (SELECT 1 FROM BANGDIEM WHERE MASV = 'SV010' AND MAMH = 'ATTT' AND LAN = 1)
BEGIN
    DECLARE @question_json_attt nvarchar(max);
    DECLARE @answer_json_attt nvarchar(max);

    SELECT @question_json_attt = N'[' + STRING_AGG(CONVERT(nvarchar(20), CAUHOI), N',') + N']'
    FROM (
        SELECT TOP (30) CAUHOI
        FROM BODE
        WHERE MAMH = 'ATTT' AND TRINHDO IN ('A', 'B')
        ORDER BY CAUHOI
    ) q;

    SELECT @answer_json_attt = N'{' + STRING_AGG(CONCAT(N'"', CAUHOI, N'":"', DAP_AN, N'"'), N',') + N'}'
    FROM (
        SELECT TOP (30) CAUHOI, DAP_AN
        FROM BODE
        WHERE MAMH = 'ATTT' AND TRINHDO IN ('A', 'B')
        ORDER BY CAUHOI
    ) q;

    INSERT INTO PHIENTHI (
        MASV, MALOP, MAMH, TRINHDO, LAN, SOCAUTHI, THOIGIAN, NGAYTHI,
        BATDAU_LUC, THOIGIAN_CONLAI, TRANGTHAI, DANHSACH_CAUHOI,
        DAPAN_DACHON, CAUHOI_HIENTAI, CAPNHAT_LUC, NOPBAI_LUC, DIEM
    )
    VALUES (
        'SV010', 'D23CQCN01', 'ATTT', 'A', 1, 30, 25, CAST(GETDATE() AS date),
        DATEADD(MINUTE, -20, GETDATE()), 0, N'DA_NOP', @question_json_attt,
        @answer_json_attt, 29, GETDATE(), GETDATE(), 9.5
    );

    INSERT INTO BANGDIEM (MASV, MAMH, LAN, NGAYTHI, DIEM)
    VALUES ('SV010', 'ATTT', 1, CAST(GETDATE() AS date), 9.5);
END

IF NOT EXISTS (SELECT 1 FROM BANGDIEM WHERE MASV = 'SV013' AND MAMH = 'CNPM' AND LAN = 1)
BEGIN
    DECLARE @question_json_cnpm nvarchar(max);
    DECLARE @answer_json_cnpm nvarchar(max);

    SELECT @question_json_cnpm = N'[' + STRING_AGG(CONVERT(nvarchar(20), CAUHOI), N',') + N']'
    FROM (
        SELECT TOP (30) CAUHOI
        FROM BODE
        WHERE MAMH = 'CNPM' AND TRINHDO IN ('B', 'C')
        ORDER BY CAUHOI
    ) q;

    SELECT @answer_json_cnpm = N'{' + STRING_AGG(CONCAT(N'"', CAUHOI, N'":"', CASE WHEN DAP_AN = 'B' THEN 'B' ELSE 'A' END, N'"'), N',') + N'}'
    FROM (
        SELECT TOP (30) CAUHOI, DAP_AN
        FROM BODE
        WHERE MAMH = 'CNPM' AND TRINHDO IN ('B', 'C')
        ORDER BY CAUHOI
    ) q;

    INSERT INTO PHIENTHI (
        MASV, MALOP, MAMH, TRINHDO, LAN, SOCAUTHI, THOIGIAN, NGAYTHI,
        BATDAU_LUC, THOIGIAN_CONLAI, TRANGTHAI, DANHSACH_CAUHOI,
        DAPAN_DACHON, CAUHOI_HIENTAI, CAPNHAT_LUC, NOPBAI_LUC, DIEM
    )
    VALUES (
        'SV013', 'D23CQCN02', 'CNPM', 'B', 1, 30, 25, CAST(GETDATE() AS date),
        DATEADD(MINUTE, -25, GETDATE()), 0, N'DA_NOP', @question_json_cnpm,
        @answer_json_cnpm, 29, GETDATE(), GETDATE(), 8
    );

    INSERT INTO BANGDIEM (MASV, MAMH, LAN, NGAYTHI, DIEM)
    VALUES ('SV013', 'CNPM', 1, CAST(GETDATE() AS date), 8);
END
GO

SELECT 'More demo data seeded successfully' AS Message;
GO
