USE hqtcsdl;
GO

IF NOT EXISTS (SELECT 1 FROM MONHOC WHERE MAMH = 'CTDL') INSERT INTO MONHOC (MAMH, TENMH) VALUES ('CTDL', N'Cau truc du lieu');
IF NOT EXISTS (SELECT 1 FROM MONHOC WHERE MAMH = 'LTHDT') INSERT INTO MONHOC (MAMH, TENMH) VALUES ('LTHDT', N'Lap trinh huong doi tuong');
IF NOT EXISTS (SELECT 1 FROM MONHOC WHERE MAMH = 'HQT') INSERT INTO MONHOC (MAMH, TENMH) VALUES ('HQT', N'He quan tri CSDL');
GO

IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = 'D21CQCN03') INSERT INTO LOP (MALOP, TENLOP) VALUES ('D21CQCN03', N'Dai hoc CNTT 03');
IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = 'D22CQCN01') INSERT INTO LOP (MALOP, TENLOP) VALUES ('D22CQCN01', N'Dai hoc CNTT K22 01');
IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = 'D22CQCN02') INSERT INTO LOP (MALOP, TENLOP) VALUES ('D22CQCN02', N'Dai hoc CNTT K22 02');
GO

IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV004') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV004', N'Nguyen Hoai', N'Nam', '2004-01-11', N'TP HCM', 'D21CQCN02', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV005') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV005', N'Tran Minh', N'Thu', '2004-03-19', N'Tay Ninh', 'D21CQCN03', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV006') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV006', N'Pham Gia', N'Huy', '2004-05-23', N'Long An', 'D21CQCN03', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV007') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV007', N'Do Quynh', N'Anh', '2004-08-14', N'Binh Duong', 'D22CQCN01', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV008') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV008', N'Bui Thanh', N'Lam', '2004-10-05', N'Dong Nai', 'D22CQCN01', '123456');
IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = 'SV009') INSERT INTO SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) VALUES ('SV009', N'Vo Ngoc', N'Linh', '2004-12-01', N'TP HCM', 'D22CQCN02', '123456');
GO

DECLARE @subjects TABLE (MAMH nchar(5), MAGV nchar(8));
INSERT INTO @subjects (MAMH, MAGV) VALUES ('CSDL', 'GV001'), ('CTDL', 'GV001'), ('HQT', 'GV001'), ('MMT', 'GV002'), ('LTHDT', 'GV002');

DECLARE @levels TABLE (TRINHDO char(1), DAP_AN char(1));
INSERT INTO @levels (TRINHDO, DAP_AN) VALUES ('A', 'A'), ('B', 'B'), ('C', 'C');

DECLARE @mamh nchar(5), @magv nchar(8), @level char(1), @answer char(1), @i int;
DECLARE subject_cursor CURSOR LOCAL FAST_FORWARD FOR SELECT MAMH, MAGV FROM @subjects;
OPEN subject_cursor;
FETCH NEXT FROM subject_cursor INTO @mamh, @magv;
WHILE @@FETCH_STATUS = 0
BEGIN
    DECLARE level_cursor CURSOR LOCAL FAST_FORWARD FOR SELECT TRINHDO, DAP_AN FROM @levels;
    OPEN level_cursor;
    FETCH NEXT FROM level_cursor INTO @level, @answer;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @i = 1;
        WHILE @i <= 50
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM BODE
                WHERE MAMH = @mamh AND TRINHDO = @level AND NOIDUNG = CONCAT(RTRIM(@mamh), N' ', @level, N' demo cau ', @i)
            )
            BEGIN
                INSERT INTO BODE (MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV)
                VALUES (
                    @mamh,
                    @level,
                    CONCAT(RTRIM(@mamh), N' ', @level, N' demo cau ', @i),
                    CONCAT(N'Lua chon A cho cau ', @i),
                    CONCAT(N'Lua chon B cho cau ', @i),
                    CONCAT(N'Lua chon C cho cau ', @i),
                    CONCAT(N'Lua chon D cho cau ', @i),
                    @answer,
                    @magv
                );
            END
            SET @i += 1;
        END
        FETCH NEXT FROM level_cursor INTO @level, @answer;
    END
    CLOSE level_cursor;
    DEALLOCATE level_cursor;

    FETCH NEXT FROM subject_cursor INTO @mamh, @magv;
END
CLOSE subject_cursor;
DEALLOCATE subject_cursor;
GO

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN_DANGKY WHERE MALOP = 'D21CQCN01' AND MAMH = 'CTDL' AND LAN = 1)
    INSERT INTO GIAOVIEN_DANGKY (MALOP, MAMH, LAN, MAGV, TRINHDO, NGAYTHI, SOCAUTHI, THOIGIAN)
    VALUES ('D21CQCN01', 'CTDL', 1, 'GV001', 'B', DATEADD(DAY, 1, GETDATE()), 40, 30);

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN_DANGKY WHERE MALOP = 'D21CQCN02' AND MAMH = 'HQT' AND LAN = 1)
    INSERT INTO GIAOVIEN_DANGKY (MALOP, MAMH, LAN, MAGV, TRINHDO, NGAYTHI, SOCAUTHI, THOIGIAN)
    VALUES ('D21CQCN02', 'HQT', 1, 'GV001', 'A', DATEADD(DAY, 2, GETDATE()), 40, 30);

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN_DANGKY WHERE MALOP = 'D22CQCN01' AND MAMH = 'MMT' AND LAN = 1)
    INSERT INTO GIAOVIEN_DANGKY (MALOP, MAMH, LAN, MAGV, TRINHDO, NGAYTHI, SOCAUTHI, THOIGIAN)
    VALUES ('D22CQCN01', 'MMT', 1, 'GV002', 'B', DATEADD(DAY, 1, GETDATE()), 40, 30);

IF NOT EXISTS (SELECT 1 FROM GIAOVIEN_DANGKY WHERE MALOP = 'D22CQCN02' AND MAMH = 'LTHDT' AND LAN = 1)
    INSERT INTO GIAOVIEN_DANGKY (MALOP, MAMH, LAN, MAGV, TRINHDO, NGAYTHI, SOCAUTHI, THOIGIAN)
    VALUES ('D22CQCN02', 'LTHDT', 1, 'GV002', 'C', DATEADD(DAY, 3, GETDATE()), 40, 30);
GO

SELECT 'More demo data seeded successfully' AS Message;
GO
